network: "GBreducednetwork_OPFLearn"
seed: 42
data:
  input_dim: 9
  output_dim: 6
  edge_dim: 2
  # Normalization method to use. Available options:
  # - "minmax": Scales data between the minimum and maximum values.
  # - "standard": Standardizes data to have zero mean and unit variance.
  # - "baseMVAnorm": Divides data by a baseMVA value for normalization, need to specify the baseMVA parameter separately
  # - "identity": Does not apply any normalization, leaves data unchanged.
  normalization: "minmax"
  mask_dim: 6
  mask_ratio: 0.5
  mask_value: -1.0
  learn_mask: False
  scenarios: 99000
training:
  batch_size: 32
  num_layers: 3
  hidden_size: 256
  attention_head: 12
  epochs: 100
optimizer:
  learning_rate: 0.00005
  beta1: 0.9
  beta2: 0.999
  lr_decay: 0.7
  lr_patience: 3
data_split:
  val_ratio: 0.1
  test_ratio: 0.1