seed: 42
verbose: False
data:
  networks: ["case240_pserc", "case24_ieee_rts", "case30_ieee", "case57_ieee", "case89_pegase", "case118_ieee"]
  scenarios: [100000, 100000, 100000, 100000, 100000, 100000]
  normalization: "baseMVAnorm"
  baseMVA: 100
  mask_type: 'rnd'
  mask_value: 0.0
  mask_ratio: 0.5
  mask_dim: 6
  learn_mask: False
  val_ratio: 0.1
  test_ratio: 0.1
model:
  type: "GPSTransformer"
  input_dim: 9
  output_dim: 6
  edge_dim: 2
  pe_dim: 20
  num_layers: 10
  hidden_size: 256
  attention_head: 8
  dropout: 0.0
training:
  batch_size: 64
  epochs: 100
  losses: ["MaskedMSE", "PBE"]
  loss_weights: [0.01, 0.99]
optimizer:
  learning_rate: 0.0001
  beta1: 0.9
  beta2: 0.999
  lr_decay: 0.7
  lr_patience: 5
callbacks:
  patience: -1 
  tol: 0 
